// Language translations for Qumus platform
export const translations: Record<string, Record<string, string>> = {
  en: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': 'Autonomous Orchestration Engine',
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.gps': 'GPS Map',
    'nav.preferences': 'Preferences',
    'map.title': 'Flat World Map',
    'map.zoom_in': 'Zoom In',
    'map.zoom_out': 'Zoom Out',
    'map.reset': 'Reset',
    'map.locations': 'Tracked Locations',
    'broadcast.title': 'HybridCast Broadcasting',
    'broadcast.status': 'Status',
    'broadcast.viewers': 'Viewers',
    'broadcast.start': 'Start Broadcast',
    'broadcast.stop': 'Stop Broadcast',
    'translator.language': 'Language',
    'translator.select': 'Select Language',
    'chat.welcome': 'Welcome to Qumus Chat',
    'chat.send': 'Send Message',
    'preferences.title': 'User Preferences',
    'preferences.theme': 'Theme',
    'preferences.language': 'Language',
    'preferences.notifications': 'Notifications',
  },
  es: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': 'Motor de Orquestación Autónoma',
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel de Control',
    'nav.chat': 'Chat',
    'nav.gps': 'Mapa GPS',
    'nav.preferences': 'Preferencias',
    'map.title': 'Mapa Plano del Mundo',
    'map.zoom_in': 'Acercar',
    'map.zoom_out': 'Alejar',
    'map.reset': 'Restablecer',
    'map.locations': 'Ubicaciones Rastreadas',
    'broadcast.title': 'Transmisión HybridCast',
    'broadcast.status': 'Estado',
    'broadcast.viewers': 'Espectadores',
    'broadcast.start': 'Iniciar Transmisión',
    'broadcast.stop': 'Detener Transmisión',
    'translator.language': 'Idioma',
    'translator.select': 'Seleccionar Idioma',
    'chat.welcome': 'Bienvenido al Chat de Qumus',
    'chat.send': 'Enviar Mensaje',
    'preferences.title': 'Preferencias del Usuario',
    'preferences.theme': 'Tema',
    'preferences.language': 'Idioma',
    'preferences.notifications': 'Notificaciones',
  },
  fr: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': 'Moteur d\'Orchestration Autonome',
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de Bord',
    'nav.chat': 'Chat',
    'nav.gps': 'Carte GPS',
    'nav.preferences': 'Préférences',
    'map.title': 'Carte Plane du Monde',
    'map.zoom_in': 'Zoomer',
    'map.zoom_out': 'Dézoomer',
    'map.reset': 'Réinitialiser',
    'map.locations': 'Emplacements Suivis',
    'broadcast.title': 'Diffusion HybridCast',
    'broadcast.status': 'Statut',
    'broadcast.viewers': 'Spectateurs',
    'broadcast.start': 'Démarrer la Diffusion',
    'broadcast.stop': 'Arrêter la Diffusion',
    'translator.language': 'Langue',
    'translator.select': 'Sélectionner la Langue',
    'chat.welcome': 'Bienvenue au Chat Qumus',
    'chat.send': 'Envoyer le Message',
    'preferences.title': 'Préférences Utilisateur',
    'preferences.theme': 'Thème',
    'preferences.language': 'Langue',
    'preferences.notifications': 'Notifications',
  },
  de: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': 'Autonomes Orchestrierungs-Engine',
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.gps': 'GPS-Karte',
    'nav.preferences': 'Einstellungen',
    'map.title': 'Flache Weltkarte',
    'map.zoom_in': 'Vergrößern',
    'map.zoom_out': 'Verkleinern',
    'map.reset': 'Zurücksetzen',
    'map.locations': 'Verfolgter Standorte',
    'broadcast.title': 'HybridCast-Übertragung',
    'broadcast.status': 'Status',
    'broadcast.viewers': 'Zuschauer',
    'broadcast.start': 'Übertragung Starten',
    'broadcast.stop': 'Übertragung Beenden',
    'translator.language': 'Sprache',
    'translator.select': 'Sprache Wählen',
    'chat.welcome': 'Willkommen im Qumus-Chat',
    'chat.send': 'Nachricht Senden',
    'preferences.title': 'Benutzereinstellungen',
    'preferences.theme': 'Design',
    'preferences.language': 'Sprache',
    'preferences.notifications': 'Benachrichtigungen',
  },
  ja: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': '自律型オーケストレーションエンジン',
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.chat': 'チャット',
    'nav.gps': 'GPSマップ',
    'nav.preferences': '設定',
    'map.title': 'フラットワールドマップ',
    'map.zoom_in': 'ズームイン',
    'map.zoom_out': 'ズームアウト',
    'map.reset': 'リセット',
    'map.locations': 'トラッキング位置',
    'broadcast.title': 'HybridCast ブロードキャスト',
    'broadcast.status': 'ステータス',
    'broadcast.viewers': 'ビューアー',
    'broadcast.start': 'ブロードキャスト開始',
    'broadcast.stop': 'ブロードキャスト停止',
    'translator.language': '言語',
    'translator.select': '言語を選択',
    'chat.welcome': 'Qumusチャットへようこそ',
    'chat.send': 'メッセージを送信',
    'preferences.title': 'ユーザー設定',
    'preferences.theme': 'テーマ',
    'preferences.language': '言語',
    'preferences.notifications': '通知',
  },
  zh: {
    'app.title': 'Rockin Rockin Boogie',
    'app.subtitle': '自主编排引擎',
    'nav.home': '主页',
    'nav.dashboard': '仪表板',
    'nav.chat': '聊天',
    'nav.gps': 'GPS地图',
    'nav.preferences': '偏好设置',
    'map.title': '平面世界地图',
    'map.zoom_in': '放大',
    'map.zoom_out': '缩小',
    'map.reset': '重置',
    'map.locations': '跟踪位置',
    'broadcast.title': 'HybridCast 广播',
    'broadcast.status': '状态',
    'broadcast.viewers': '观众',
    'broadcast.start': '开始广播',
    'broadcast.stop': '停止广播',
    'translator.language': '语言',
    'translator.select': '选择语言',
    'chat.welcome': '欢迎来到Qumus聊天',
    'chat.send': '发送消息',
    'preferences.title': '用户偏好设置',
    'preferences.theme': '主题',
    'preferences.language': '语言',
    'preferences.notifications': '通知',
  },
};

export type Language = keyof typeof translations;

export const languages: { code: Language; name: string }[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ja', name: '日本語' },
  { code: 'zh', name: '中文' },
];

export function translate(key: string, language: Language = 'en'): string {
  return translations[language]?.[key] || translations['en']?.[key] || key;
}

export function useTranslator(language: Language = 'en') {
  return (key: string) => translate(key, language);
}
