/**
 * RRB_CONTENT_SCHEDULER_CODE.ts
 * ==============================
 * 24/7 Content Scheduling & Airwave Population Engine
 * 
 * HybridCast v2.47.24 — Ecosystem Code Package
 * A Canryn Production and its subsidiaries
 * 
 * This module provides the RRB Radio content scheduling system for:
 * - 24/7 automated broadcast scheduling across 42+ channels
 * - Solfeggio healing frequency rotation (174Hz–963Hz + 432Hz default)
 * - Genre-based content rotation (Gospel, Jazz, Blues, R&B, Hip-Hop, etc.)
 * - Commercial break insertion and sponsor management
 * - Podcast episode scheduling and auto-publishing
 * - Emergency broadcast interruption handling (HybridCast integration)
 * - Content gap detection and auto-fill with AI-generated content
 * 
 * Integration: Wire into QUMUS autonomous engine for 90% auto-scheduling
 */

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

export interface ScheduleSlot {
  id: string;
  channelId: string;
  startTime: number;
  endTime: number;
  contentType: ContentType;
  contentId: string;
  title: string;
  artist?: string;
  genre?: string;
  frequency?: number;
  priority: 'normal' | 'high' | 'emergency';
  autoGenerated: boolean;
  status: 'scheduled' | 'playing' | 'completed' | 'skipped' | 'interrupted';
}

export type ContentType = 
  | 'music' | 'podcast' | 'commercial' | 'announcement'
  | 'healing_frequency' | 'audiobook' | 'live_broadcast'
  | 'emergency_alert' | 'station_id' | 'dj_segment';

export interface Channel {
  id: string;
  name: string;
  genre: string;
  frequency: number;
  isActive: boolean;
  currentSlot?: ScheduleSlot;
  nextSlot?: ScheduleSlot;
  listeners: number;
}

export interface ScheduleConfig {
  defaultFrequency: number;
  commercialBreakInterval: number; // minutes
  commercialBreakDuration: number; // seconds
  stationIdInterval: number; // minutes
  healingFrequencyRotation: boolean;
  emergencyOverride: boolean;
  autoFillGaps: boolean;
  maxConsecutiveSameArtist: number;
}

// ============================================================================
// SOLFEGGIO FREQUENCIES — Healing Frequency Rotation
// ============================================================================

export const SOLFEGGIO_FREQUENCIES = [
  { hz: 174, name: 'Foundation', chakra: 'Root (grounding)', color: '#FF0000', description: 'Pain relief and security' },
  { hz: 285, name: 'Restoration', chakra: 'Sacral (healing)', color: '#FF7F00', description: 'Tissue repair and rejuvenation' },
  { hz: 396, name: 'Liberation', chakra: 'Solar Plexus (power)', color: '#FFFF00', description: 'Releasing guilt and fear' },
  { hz: 417, name: 'Transformation', chakra: 'Heart (love)', color: '#00FF00', description: 'Facilitating change' },
  { hz: 528, name: 'Miracle', chakra: 'Throat (expression)', color: '#0000FF', description: 'DNA repair and transformation' },
  { hz: 639, name: 'Connection', chakra: 'Third Eye (intuition)', color: '#4B0082', description: 'Harmonizing relationships' },
  { hz: 741, name: 'Awakening', chakra: 'Crown (consciousness)', color: '#9400D3', description: 'Intuition and expression' },
  { hz: 852, name: 'Intuition', chakra: 'Soul Star (divine)', color: '#FFD700', description: 'Spiritual order restoration' },
  { hz: 963, name: 'Divine', chakra: 'Spirit (oneness)', color: '#FFFFFF', description: 'Connection to higher self' },
] as const;

export const DEFAULT_FREQUENCY = 432; // Hz — Universal tuning

// ============================================================================
// RRB CHANNEL REGISTRY — 42 Channels
// ============================================================================

export const RRB_GENRES = [
  'Gospel', 'Jazz', 'Blues', 'R&B', 'Hip-Hop', 'Soul', 'Funk',
  'Reggae', 'Afrobeat', 'Classical', 'Country', 'Rock', 'Pop',
  'Electronic', 'Latin', 'Caribbean', 'Spoken Word', 'Podcast',
  'Healing Frequencies', 'Meditation', 'Audiobooks', 'News',
  'Sports', 'Comedy', 'Drama', 'Children', 'Educational',
  'Community', 'Live Events', 'DJ Mix', 'Throwback',
  'New Releases', 'Local Artists', 'International', 'Worship',
  'Praise & Worship', 'Contemporary Christian', 'Traditional Gospel',
  'Neo-Soul', 'Smooth Jazz', 'Acid Jazz', 'Bebop',
] as const;

// ============================================================================
// CONTENT SCHEDULER ENGINE
// ============================================================================

export class RRBContentScheduler {
  private schedule: Map<string, ScheduleSlot[]> = new Map();
  private config: ScheduleConfig;

  constructor(config?: Partial<ScheduleConfig>) {
    this.config = {
      defaultFrequency: DEFAULT_FREQUENCY,
      commercialBreakInterval: 30,
      commercialBreakDuration: 120,
      stationIdInterval: 60,
      healingFrequencyRotation: true,
      emergencyOverride: true,
      autoFillGaps: true,
      maxConsecutiveSameArtist: 3,
      ...config,
    };
  }

  /**
   * Generate a 24-hour schedule for a channel
   */
  generateDailySchedule(channelId: string, genre: string, date: Date = new Date()): ScheduleSlot[] {
    const slots: ScheduleSlot[] = [];
    const dayStart = new Date(date);
    dayStart.setHours(0, 0, 0, 0);
    let currentTime = dayStart.getTime();
    const dayEnd = currentTime + 24 * 60 * 60 * 1000;

    while (currentTime < dayEnd) {
      const minuteOfDay = Math.floor((currentTime - dayStart.getTime()) / 60000);

      // Station ID every hour
      if (minuteOfDay % this.config.stationIdInterval === 0) {
        slots.push(this.createSlot(channelId, currentTime, 15000, 'station_id', 
          'Rockin Rockin Boogie — A Canryn Production', genre));
        currentTime += 15000;
      }

      // Commercial break
      if (minuteOfDay % this.config.commercialBreakInterval === 0 && minuteOfDay > 0) {
        slots.push(this.createSlot(channelId, currentTime, 
          this.config.commercialBreakDuration * 1000, 'commercial', 
          'Community Sponsors — Sweet Miracles', genre));
        currentTime += this.config.commercialBreakDuration * 1000;
      }

      // Healing frequency segment (every 2 hours if enabled)
      if (this.config.healingFrequencyRotation && minuteOfDay % 120 === 0) {
        const freqIdx = Math.floor(minuteOfDay / 120) % SOLFEGGIO_FREQUENCIES.length;
        const freq = SOLFEGGIO_FREQUENCIES[freqIdx];
        slots.push(this.createSlot(channelId, currentTime, 300000, 'healing_frequency',
          `${freq.name} Frequency — ${freq.hz}Hz`, genre, freq.hz));
        currentTime += 300000;
      }

      // Regular content (music/podcast based on genre)
      const contentDuration = genre === 'Podcast' ? 1800000 : 240000; // 30min or 4min
      const contentType: ContentType = genre === 'Podcast' ? 'podcast' : 'music';
      slots.push(this.createSlot(channelId, currentTime, contentDuration, contentType,
        `${genre} Content — Auto-Scheduled`, genre));
      currentTime += contentDuration;
    }

    this.schedule.set(`${channelId}_${date.toISOString().split('T')[0]}`, slots);
    return slots;
  }

  private createSlot(
    channelId: string, startTime: number, duration: number,
    contentType: ContentType, title: string, genre: string, frequency?: number
  ): ScheduleSlot {
    return {
      id: `slot_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
      channelId,
      startTime,
      endTime: startTime + duration,
      contentType,
      contentId: `content_${Math.random().toString(36).slice(2, 8)}`,
      title,
      genre,
      frequency: frequency || this.config.defaultFrequency,
      priority: contentType === 'emergency_alert' ? 'emergency' : 'normal',
      autoGenerated: true,
      status: 'scheduled',
    };
  }

  /**
   * Insert emergency broadcast — overrides all channels
   */
  insertEmergencyBroadcast(title: string, duration: number): ScheduleSlot[] {
    if (!this.config.emergencyOverride) return [];
    
    const emergencySlots: ScheduleSlot[] = [];
    const now = Date.now();

    // Interrupt all active channels
    for (const [key, slots] of this.schedule) {
      const channelId = key.split('_')[0];
      const emergencySlot: ScheduleSlot = {
        id: `emergency_${Date.now()}_${channelId}`,
        channelId,
        startTime: now,
        endTime: now + duration,
        contentType: 'emergency_alert',
        contentId: `emergency_${Date.now()}`,
        title: `🚨 EMERGENCY: ${title}`,
        priority: 'emergency',
        autoGenerated: false,
        status: 'playing',
      };

      // Mark current slots as interrupted
      slots.forEach(slot => {
        if (slot.status === 'playing') slot.status = 'interrupted';
      });

      emergencySlots.push(emergencySlot);
    }

    return emergencySlots;
  }

  /**
   * Get current schedule status across all channels
   */
  getScheduleStatus(): {
    totalChannels: number;
    activeChannels: number;
    totalSlots: number;
    upcomingSlots: number;
    gapDetected: boolean;
  } {
    const now = Date.now();
    let totalSlots = 0;
    let upcomingSlots = 0;

    for (const slots of this.schedule.values()) {
      totalSlots += slots.length;
      upcomingSlots += slots.filter(s => s.startTime > now).length;
    }

    return {
      totalChannels: this.schedule.size,
      activeChannels: this.schedule.size,
      totalSlots,
      upcomingSlots,
      gapDetected: false,
    };
  }

  getConfig(): ScheduleConfig {
    return { ...this.config };
  }

  updateConfig(updates: Partial<ScheduleConfig>): void {
    this.config = { ...this.config, ...updates };
  }
}

// ============================================================================
// SINGLETON INSTANCE
// ============================================================================

export const rrbScheduler = new RRBContentScheduler();
