DROP TABLE `activity_logs`;--> statement-breakpoint
DROP TABLE `admin_logs`;--> statement-breakpoint
DROP TABLE `agent_certifications`;--> statement-breakpoint
DROP TABLE `agent_collaboration`;--> statement-breakpoint
DROP TABLE `agent_execution_logs`;--> statement-breakpoint
DROP TABLE `agent_installations`;--> statement-breakpoint
DROP TABLE `agent_marketplace`;--> statement-breakpoint
DROP TABLE `agent_memory`;--> statement-breakpoint
DROP TABLE `agent_performance_metrics`;--> statement-breakpoint
DROP TABLE `agent_profiles`;--> statement-breakpoint
DROP TABLE `agent_registry`;--> statement-breakpoint
DROP TABLE `agent_reviews`;--> statement-breakpoint
DROP TABLE `agent_rollbacks`;--> statement-breakpoint
DROP TABLE `agent_sessions`;--> statement-breakpoint
DROP TABLE `agent_snapshots`;--> statement-breakpoint
DROP TABLE `agent_tools`;--> statement-breakpoint
DROP TABLE `agent_versions`;--> statement-breakpoint
DROP TABLE `agents`;--> statement-breakpoint
DROP TABLE `alert_broadcast_log`;--> statement-breakpoint
DROP TABLE `alert_delivery_log`;--> statement-breakpoint
DROP TABLE `alert_rules`;--> statement-breakpoint
DROP TABLE `alerts`;--> statement-breakpoint
DROP TABLE `analytics_history`;--> statement-breakpoint
DROP TABLE `analytics_metrics`;--> statement-breakpoint
DROP TABLE `anomaly_baselines`;--> statement-breakpoint
DROP TABLE `anomaly_history`;--> statement-breakpoint
DROP TABLE `anomaly_insights`;--> statement-breakpoint
DROP TABLE `anomaly_patterns`;--> statement-breakpoint
DROP TABLE `anomaly_reports`;--> statement-breakpoint
DROP TABLE `anomaly_rules`;--> statement-breakpoint
DROP TABLE `api_keys`;--> statement-breakpoint
DROP TABLE `api_usage`;--> statement-breakpoint
DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `auto_save_settings`;--> statement-breakpoint
DROP TABLE `batch_jobs`;--> statement-breakpoint
DROP TABLE `batch_queues`;--> statement-breakpoint
DROP TABLE `batch_video_jobs`;--> statement-breakpoint
DROP TABLE `certification_audits`;--> statement-breakpoint
DROP TABLE `cloned_sessions`;--> statement-breakpoint
DROP TABLE `collaboration_invites`;--> statement-breakpoint
DROP TABLE `conflict_resolution`;--> statement-breakpoint
DROP TABLE `content_listener_history`;--> statement-breakpoint
DROP TABLE `cost_analysis`;--> statement-breakpoint
DROP TABLE `cost_optimizations`;--> statement-breakpoint
DROP TABLE `detected_anomalies`;--> statement-breakpoint
DROP TABLE `donations`;--> statement-breakpoint
DROP TABLE `email_configs`;--> statement-breakpoint
DROP TABLE `emergency_alerts`;--> statement-breakpoint
DROP TABLE `escalation_policies`;--> statement-breakpoint
DROP TABLE `feature_flags`;--> statement-breakpoint
DROP TABLE `filter_history`;--> statement-breakpoint
DROP TABLE `filter_presets`;--> statement-breakpoint
DROP TABLE `finetuning_datasets`;--> statement-breakpoint
DROP TABLE `finetuning_evaluations`;--> statement-breakpoint
DROP TABLE `finetuning_jobs`;--> statement-breakpoint
DROP TABLE `finetuning_models`;--> statement-breakpoint
DROP TABLE `hybridcast_nodes`;--> statement-breakpoint
DROP TABLE `integration_logs`;--> statement-breakpoint
DROP TABLE `integrations`;--> statement-breakpoint
DROP TABLE `meditation_progress`;--> statement-breakpoint
DROP TABLE `meditation_sessions`;--> statement-breakpoint
DROP TABLE `meditation_stats`;--> statement-breakpoint
DROP TABLE `memory_store`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `model_comparisons`;--> statement-breakpoint
DROP TABLE `notification_events`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `orchestration_results`;--> statement-breakpoint
DROP TABLE `orchestration_tasks`;--> statement-breakpoint
DROP TABLE `performance_benchmarks`;--> statement-breakpoint
DROP TABLE `performance_metrics`;--> statement-breakpoint
DROP TABLE `performance_trends`;--> statement-breakpoint
DROP TABLE `platform_metrics_history`;--> statement-breakpoint
DROP TABLE `plugins`;--> statement-breakpoint
DROP TABLE `podcast_channels`;--> statement-breakpoint
DROP TABLE `podcast_episodes`;--> statement-breakpoint
DROP TABLE `podcast_history`;--> statement-breakpoint
DROP TABLE `policy_decisions`;--> statement-breakpoint
DROP TABLE `predictive_alerts`;--> statement-breakpoint
DROP TABLE `premium_features`;--> statement-breakpoint
DROP TABLE `qumus_audit_logs`;--> statement-breakpoint
DROP TABLE `qumus_autonomous_actions`;--> statement-breakpoint
DROP TABLE `qumus_decision_policies`;--> statement-breakpoint
DROP TABLE `qumus_human_review`;--> statement-breakpoint
DROP TABLE `qumus_metrics`;--> statement-breakpoint
DROP TABLE `quota_alerts`;--> statement-breakpoint
DROP TABLE `quotas`;--> statement-breakpoint
DROP TABLE `radio_channels`;--> statement-breakpoint
DROP TABLE `radio_stations`;--> statement-breakpoint
DROP TABLE `rate_limit_events`;--> statement-breakpoint
DROP TABLE `rate_limit_rules`;--> statement-breakpoint
DROP TABLE `rate_limit_usage`;--> statement-breakpoint
DROP TABLE `realtime_metrics_cache`;--> statement-breakpoint
DROP TABLE `reasoning_chains`;--> statement-breakpoint
DROP TABLE `report_history`;--> statement-breakpoint
DROP TABLE `rockin_boogie_content`;--> statement-breakpoint
DROP TABLE `saved_templates`;--> statement-breakpoint
DROP TABLE `scenes`;--> statement-breakpoint
DROP TABLE `scheduled_reports`;--> statement-breakpoint
DROP TABLE `security_scans`;--> statement-breakpoint
DROP TABLE `session_annotations`;--> statement-breakpoint
DROP TABLE `session_collaborators`;--> statement-breakpoint
DROP TABLE `session_metrics`;--> statement-breakpoint
DROP TABLE `session_shares`;--> statement-breakpoint
DROP TABLE `session_versions`;--> statement-breakpoint
DROP TABLE `shots`;--> statement-breakpoint
DROP TABLE `storyboards`;--> statement-breakpoint
DROP TABLE `stripe_events`;--> statement-breakpoint
DROP TABLE `studio_metrics`;--> statement-breakpoint
DROP TABLE `studio_sessions`;--> statement-breakpoint
DROP TABLE `subscription_tiers`;--> statement-breakpoint
DROP TABLE `suppression_rules`;--> statement-breakpoint
DROP TABLE `swarm_coordination`;--> statement-breakpoint
DROP TABLE `system_alerts`;--> statement-breakpoint
DROP TABLE `system_metrics`;--> statement-breakpoint
DROP TABLE `task_history`;--> statement-breakpoint
DROP TABLE `team_members`;--> statement-breakpoint
DROP TABLE `teams`;--> statement-breakpoint
DROP TABLE `tool_executions`;--> statement-breakpoint
DROP TABLE `tool_usage_stats`;--> statement-breakpoint
DROP TABLE `training_data`;--> statement-breakpoint
DROP TABLE `usage_quotas`;--> statement-breakpoint
DROP TABLE `user_collaborations`;--> statement-breakpoint
DROP TABLE `user_integrations`;--> statement-breakpoint
DROP TABLE `user_subscriptions`;--> statement-breakpoint
DROP TABLE `users_stripe_mapping`;--> statement-breakpoint
DROP TABLE `video_watermarks`;--> statement-breakpoint
DROP TABLE `voice_commands`;--> statement-breakpoint
DROP TABLE `webhook_endpoints`;--> statement-breakpoint
DROP TABLE `webhook_events`;--> statement-breakpoint
DROP TABLE `webhook_installations`;--> statement-breakpoint
DROP TABLE `webhook_logs`;--> statement-breakpoint
DROP TABLE `webhook_marketplace_reviews`;--> statement-breakpoint
DROP TABLE `webhook_templates`;--> statement-breakpoint
DROP TABLE `workspace_members`;--> statement-breakpoint
DROP TABLE `workspaces`;