CREATE TABLE `call_in_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`show_id` int NOT NULL,
	`session_id` int,
	`user_id` int,
	`caller_name` varchar(255) NOT NULL,
	`caller_email` varchar(255),
	`topic` text,
	`status` enum('waiting','screening','ready','on_air','completed','dropped','rejected') NOT NULL DEFAULT 'waiting',
	`queue_position` int DEFAULT 0,
	`peer_id` varchar(255),
	`connection_type` enum('webrtc','phone','sip') NOT NULL DEFAULT 'webrtc',
	`is_muted` boolean DEFAULT true,
	`joined_at` bigint NOT NULL,
	`on_air_at` bigint,
	`ended_at` bigint,
	`duration_on_air` int,
	`rating` int,
	`notes` text,
	`created_at` bigint NOT NULL,
	CONSTRAINT `call_in_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `podcast_episodes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`show_id` int NOT NULL,
	`episode_number` int NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`audio_url` text,
	`audio_file_key` varchar(500),
	`video_url` text,
	`thumbnail_url` text,
	`duration` int,
	`file_size` int,
	`status` enum('draft','uploading','processing','ready','published','scheduled','archived') NOT NULL DEFAULT 'draft',
	`published_at` bigint,
	`scheduled_publish_at` bigint,
	`spotify_episode_id` varchar(255),
	`apple_episode_id` varchar(255),
	`youtube_video_id` varchar(255),
	`distribution_status` json,
	`play_count` int DEFAULT 0,
	`download_count` int DEFAULT 0,
	`like_count` int DEFAULT 0,
	`tags` json,
	`guest_names` json,
	`show_notes` text,
	`transcript_url` text,
	`chapters` json,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `podcast_episodes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `podcast_shows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(100) NOT NULL,
	`title` varchar(500) NOT NULL,
	`subtitle` varchar(500),
	`description` text,
	`host_persona` enum('candy','valanna','seraph') NOT NULL,
	`host_name` varchar(255) NOT NULL,
	`cover_image_url` text,
	`theme_color` varchar(20) DEFAULT '#a78bfa',
	`schedule_day` varchar(100),
	`schedule_time` varchar(50),
	`schedule_timezone` varchar(20) DEFAULT 'CT',
	`is_live` boolean DEFAULT false,
	`total_episodes` int DEFAULT 0,
	`total_listeners` int DEFAULT 0,
	`spotify_url` text,
	`apple_url` text,
	`youtube_url` text,
	`rss_feed_url` text,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `podcast_shows_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `call_in_queue` ADD CONSTRAINT `call_in_queue_show_id_podcast_shows_id_fk` FOREIGN KEY (`show_id`) REFERENCES `podcast_shows`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `call_in_queue` ADD CONSTRAINT `call_in_queue_user_id_users_id_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `podcast_episodes` ADD CONSTRAINT `podcast_episodes_show_id_podcast_shows_id_fk` FOREIGN KEY (`show_id`) REFERENCES `podcast_shows`(`id`) ON DELETE cascade ON UPDATE no action;