/**
 * Analytics Export Service
 * Generates CSV and PDF reports for listener analytics
 */

export interface ChannelAnalytics {
  channelId: string;
  channelName: string;
  date: Date;
  avgListeners: number;
  maxListeners: number;
  minListeners: number;
  totalSpikes: number;
  peakHour: number;
  topTrack: string;
  engagementRate: number;
}

export interface ExportOptions {
  startDate: Date;
  endDate: Date;
  channels: string[];
  format: 'csv' | 'pdf';
  includeCharts: boolean;
}

/**
 * Generate CSV export of analytics data
 */
export function generateAnalyticsCSV(analytics: ChannelAnalytics[]): string {
  const headers = [
    'Channel Name',
    'Date',
    'Avg Listeners',
    'Max Listeners',
    'Min Listeners',
    'Total Spikes',
    'Peak Hour',
    'Top Track',
    'Engagement Rate (%)'
  ];

  const rows = analytics.map(a => [
    a.channelName,
    a.date.toISOString().split('T')[0],
    a.avgListeners.toString(),
    a.maxListeners.toString(),
    a.minListeners.toString(),
    a.totalSpikes.toString(),
    `${a.peakHour}:00`,
    a.topTrack,
    a.engagementRate.toFixed(2)
  ]);

  // CSV format
  const csv = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  return csv;
}

/**
 * Generate PDF report header
 */
export function generatePDFHeader(
  startDate: Date,
  endDate: Date,
  channelCount: number
): string {
  return `
LISTENER ANALYTICS REPORT
Generated: ${new Date().toLocaleDateString()}
Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}
Channels: ${channelCount}

================================================================================
  `.trim();
}

/**
 * Generate PDF report body with analytics data
 */
export function generatePDFBody(analytics: ChannelAnalytics[]): string {
  const sections = analytics.map(a => `
CHANNEL: ${a.channelName}
Date: ${a.date.toLocaleDateString()}

Listener Statistics:
  • Average: ${a.avgListeners} listeners
  • Maximum: ${a.maxListeners} listeners
  • Minimum: ${a.minListeners} listeners
  • Peak Hour: ${a.peakHour}:00

Performance Metrics:
  • Listener Spikes: ${a.totalSpikes}
  • Top Track: ${a.topTrack}
  • Engagement Rate: ${a.engagementRate.toFixed(2)}%

---
  `.trim());

  return sections.join('\n\n');
}

/**
 * Generate PDF report footer with summary
 */
export function generatePDFFooter(analytics: ChannelAnalytics[]): string {
  const totalSpikes = analytics.reduce((sum, a) => sum + a.totalSpikes, 0);
  const avgEngagement = analytics.reduce((sum, a) => sum + a.engagementRate, 0) / analytics.length;
  const maxListeners = Math.max(...analytics.map(a => a.maxListeners));

  return `
================================================================================
SUMMARY

Total Channels Analyzed: ${analytics.length}
Total Listener Spikes: ${totalSpikes}
Average Engagement Rate: ${avgEngagement.toFixed(2)}%
Peak Listeners Across All Channels: ${maxListeners}

Key Insights:
• Monitor channels with high spike activity
• Investigate engagement rate variations
• Plan content around peak listening hours
• Consider capacity planning for high-traffic periods

Report Generated by RRB Analytics System
For more details, visit: /operator-dashboard
  `.trim();
}

/**
 * Generate complete PDF content
 */
export function generatePDFContent(
  analytics: ChannelAnalytics[],
  startDate: Date,
  endDate: Date
): string {
  const header = generatePDFHeader(startDate, endDate, analytics.length);
  const body = generatePDFBody(analytics);
  const footer = generatePDFFooter(analytics);

  return `${header}\n\n${body}\n\n${footer}`;
}

/**
 * Export analytics to file format
 */
export async function exportAnalytics(
  analytics: ChannelAnalytics[],
  options: ExportOptions
): Promise<{ data: string; filename: string; mimeType: string }> {
  try {
    if (options.format === 'csv') {
      const csv = generateAnalyticsCSV(analytics);
      const filename = `analytics-${options.startDate.toISOString().split('T')[0]}-to-${options.endDate.toISOString().split('T')[0]}.csv`;

      return {
        data: csv,
        filename,
        mimeType: 'text/csv'
      };
    } else {
      // PDF format
      const pdfContent = generatePDFContent(analytics, options.startDate, options.endDate);
      const filename = `analytics-${options.startDate.toISOString().split('T')[0]}-to-${options.endDate.toISOString().split('T')[0]}.txt`;

      // Note: In production, use a PDF library like pdfkit or puppeteer
      return {
        data: pdfContent,
        filename,
        mimeType: 'text/plain'
      };
    }
  } catch (error) {
    console.error('[Analytics Export] Failed:', error);
    throw new Error('Failed to export analytics');
  }
}

/**
 * Generate weekly summary report
 */
export function generateWeeklySummary(analytics: ChannelAnalytics[]): {
  totalListeners: number;
  avgListenersPerChannel: number;
  topChannel: ChannelAnalytics;
  totalSpikes: number;
  avgEngagement: number;
} {
  const totalListeners = analytics.reduce((sum, a) => sum + a.avgListeners, 0);
  const avgListenersPerChannel = totalListeners / analytics.length;
  const topChannel = analytics.reduce((max, a) => a.maxListeners > max.maxListeners ? a : max);
  const totalSpikes = analytics.reduce((sum, a) => sum + a.totalSpikes, 0);
  const avgEngagement = analytics.reduce((sum, a) => sum + a.engagementRate, 0) / analytics.length;

  return {
    totalListeners,
    avgListenersPerChannel,
    topChannel,
    totalSpikes,
    avgEngagement
  };
}

/**
 * Generate monthly trend analysis
 */
export function generateMonthlyTrend(
  weeklyAnalytics: ChannelAnalytics[][]
): {
  week: number;
  avgListeners: number;
  trend: 'up' | 'down' | 'stable';
}[] {
  return weeklyAnalytics.map((week, index) => {
    const avgListeners = week.reduce((sum, a) => sum + a.avgListeners, 0) / week.length;

    let trend: 'up' | 'down' | 'stable' = 'stable';
    if (index > 0) {
      const prevAvg = weeklyAnalytics[index - 1].reduce((sum, a) => sum + a.avgListeners, 0) / weeklyAnalytics[index - 1].length;
      if (avgListeners > prevAvg * 1.1) trend = 'up';
      else if (avgListeners < prevAvg * 0.9) trend = 'down';
    }

    return {
      week: index + 1,
      avgListeners: Math.round(avgListeners),
      trend
    };
  });
}
