import { getWebhookSystem } from './webhookEventSystem';
import { rockinBoogieService } from './rockinBoogieIntegration';

export interface AutomationRule {
  id: string;
  name: string;
  trigger: string;
  action: string;
  enabled: boolean;
  createdAt: number;
}

export class BroadcastAutomationEngine {
  private rules: Map<string, AutomationRule> = new Map();
  private webhookSystem = getWebhookSystem();

  /**
   * Initialize automation engine with default rules
   */
  async initialize(): Promise<void> {
    console.log('[Automation] Initializing broadcast automation engine');

    // Rule 1: Auto-schedule next broadcast when current one completes
    this.addRule({
      id: 'auto-schedule-next',
      name: 'Auto-schedule next broadcast',
      trigger: 'broadcast.completed',
      action: 'schedule-next-broadcast',
      enabled: true,
      createdAt: Date.now(),
    });

    // Rule 2: Auto-generate content when broadcast is scheduled
    this.addRule({
      id: 'auto-generate-content',
      name: 'Auto-generate content for broadcasts',
      trigger: 'rockin-boogie.schedule-next',
      action: 'generate-content',
      enabled: true,
      createdAt: Date.now(),
    });

    // Rule 3: Auto-insert commercials at scheduled intervals
    this.addRule({
      id: 'auto-insert-commercials',
      name: 'Auto-insert commercials',
      trigger: 'broadcast.started',
      action: 'insert-commercials',
      enabled: true,
      createdAt: Date.now(),
    });

    // Rule 4: Auto-update analytics when broadcast completes
    this.addRule({
      id: 'auto-update-analytics',
      name: 'Auto-update analytics',
      trigger: 'broadcast.completed',
      action: 'update-analytics',
      enabled: true,
      createdAt: Date.now(),
    });

    // Register webhook listeners for automation
    this.registerWebhookListeners();

    console.log('[Automation] Engine initialized with 4 default rules');
  }

  /**
   * Register webhook listeners for automation rules
   */
  private registerWebhookListeners(): void {
    // Listen for broadcast completion and auto-schedule next
    this.webhookSystem.registerListener(
      'broadcast.completed',
      async (event) => {
        console.log('[Automation] Broadcast completed, triggering auto-schedule');
        
        const nextBroadcast = rockinBoogieService.scheduleBroadcast({
          title: `Auto-scheduled Broadcast ${new Date().toLocaleTimeString()}`,
          description: 'Automatically scheduled by QUMUS automation engine',
          startTime: Date.now() + 3600000, // 1 hour from now
          endTime: Date.now() + 7200000, // 2 hours from now
          musicTracks: [],
          commercials: [],
          contentType: 'mixed',
          autonomyLevel: 85,
          autoGenerated: true,
        });

        // Emit event for next broadcast
        await this.webhookSystem.emitEvent(
          'rockin-boogie.schedule-next',
          {
            broadcastId: nextBroadcast.id,
            scheduledTime: nextBroadcast.startTime,
            contentType: nextBroadcast.contentType,
          },
          'automation-engine'
        );
      },
      'RRB-Automation'
    );

    // Listen for scheduled broadcasts and auto-generate content
    this.webhookSystem.registerListener(
      'rockin-boogie.schedule-next',
      async (event) => {
        console.log('[Automation] Scheduled broadcast, triggering content generation');
        
        // Auto-generate content
        await this.webhookSystem.emitEvent(
          'content.generate',
          {
            broadcastId: event.data.broadcastId,
            contentType: event.data.contentType || 'mixed',
            autoGenerated: true,
          },
          'automation-engine'
        );
      },
      'RRB-Automation'
    );

    // Listen for content generation completion
    this.webhookSystem.registerListener(
      'content.generated',
      async (event) => {
        console.log('[Automation] Content generated, updating RRB');
        
        // Update RRB with generated content
        await this.webhookSystem.emitEvent(
          'rockin-boogie.content-ready',
          {
            contentId: event.data.contentId,
            contentType: event.data.contentType,
            broadcastId: event.data.broadcastId,
          },
          'automation-engine'
        );
      },
      'RRB-Automation'
    );

    // Listen for broadcast start and auto-insert commercials
    this.webhookSystem.registerListener(
      'broadcast.started',
      async (event) => {
        console.log('[Automation] Broadcast started, inserting commercials');
        
        // Insert commercials at 25% and 75% marks
        await this.webhookSystem.emitEvent(
          'broadcast.insert-commercial',
          {
            broadcastId: event.data.broadcastId,
            position: 0.25,
            duration: 30,
          },
          'automation-engine'
        );

        // Schedule second commercial
        setTimeout(async () => {
          await this.webhookSystem.emitEvent(
            'broadcast.insert-commercial',
            {
              broadcastId: event.data.broadcastId,
              position: 0.75,
              duration: 30,
            },
            'automation-engine'
          );
        }, (event.data.duration || 3600) * 1000 * 0.5); // Half way through broadcast
      },
      'RRB-Automation'
    );

    console.log('[Automation] Webhook listeners registered');
  }

  /**
   * Add automation rule
   */
  addRule(rule: AutomationRule): void {
    this.rules.set(rule.id, rule);
    console.log(`[Automation] Rule added: ${rule.name}`);
  }

  /**
   * Remove automation rule
   */
  removeRule(ruleId: string): boolean {
    const removed = this.rules.delete(ruleId);
    if (removed) {
      console.log(`[Automation] Rule removed: ${ruleId}`);
    }
    return removed;
  }

  /**
   * Enable automation rule
   */
  enableRule(ruleId: string): boolean {
    const rule = this.rules.get(ruleId);
    if (rule) {
      rule.enabled = true;
      console.log(`[Automation] Rule enabled: ${rule.name}`);
      return true;
    }
    return false;
  }

  /**
   * Disable automation rule
   */
  disableRule(ruleId: string): boolean {
    const rule = this.rules.get(ruleId);
    if (rule) {
      rule.enabled = false;
      console.log(`[Automation] Rule disabled: ${rule.name}`);
      return true;
    }
    return false;
  }

  /**
   * Get all automation rules
   */
  getRules(): AutomationRule[] {
    return Array.from(this.rules.values());
  }

  /**
   * Get enabled automation rules
   */
  getEnabledRules(): AutomationRule[] {
    return Array.from(this.rules.values()).filter((rule) => rule.enabled);
  }

  /**
   * Trigger manual automation
   */
  async triggerManualAutomation(trigger: string): Promise<void> {
    console.log(`[Automation] Manual trigger: ${trigger}`);
    
    // Find rules matching this trigger
    const matchingRules = Array.from(this.rules.values()).filter(
      (rule) => rule.trigger === trigger && rule.enabled
    );

    for (const rule of matchingRules) {
      console.log(`[Automation] Executing rule: ${rule.name}`);
      
      // Emit webhook event for the trigger
      await this.webhookSystem.emitEvent(trigger, {
        manualTrigger: true,
        timestamp: Date.now(),
      }, 'automation-engine');
    }
  }
}

// Singleton instance
let automationEngine: BroadcastAutomationEngine | null = null;

/**
 * Get or create automation engine
 */
export function getAutomationEngine(): BroadcastAutomationEngine {
  if (!automationEngine) {
    automationEngine = new BroadcastAutomationEngine();
  }
  return automationEngine;
}

/**
 * Initialize automation engine
 */
export async function initializeAutomationEngine(): Promise<void> {
  const engine = getAutomationEngine();
  await engine.initialize();
}
